In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available")

GPU is available
Using GPU: Tesla T4


Creating Tensor

In [ ]:
#using empty
torch.empty(2,3) #allocates 2,3 of memory in space does not do anything else, doesnt add anything just creates memory

tensor([[-8.5962e+05,  4.3945e-41, -8.5962e+05],
        [ 4.3945e-41,  0.0000e+00,  0.0000e+00]])

In [ ]:
#check type
a = torch.empty(1,1)
type(a)

torch.Tensor

In [ ]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3) #generates random values at each run

tensor([[0.9418, 0.5814, 0.6506],
        [0.5486, 0.4456, 0.3111]])

In [ ]:
#define seed to keep same values ones generated
torch.manual_seed(1729)
torch.rand(2,3)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])

In [ ]:
torch.tensor([[1,2,3],[2,3,4]])

tensor([[1, 2, 3],
        [2, 3, 4]])

In [ ]:
torch.arange(10,50,5)

tensor([10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

## Tensor Shape

In [ ]:
x = torch.tensor([[1,2,3],[2,3,4]])
print(x.shape)

torch.Size([2, 3])


In [ ]:
torch.empty_like(x)
#creates an empty tensor of the shape of the x

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 7305455856218826290]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x)
#why error cause rand genrates random float values and our tensor is of integer type so we have to explicitly we have to tell taht we want float type of values

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

## Tensor Data Type

In [ ]:
x

tensor([[1, 2, 3],
        [2, 3, 4]])

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [2., 3., 4.]])

mathematical operations

In [ ]:
#scalar operation
x = torch.rand(2,3)

In [ ]:
print(x+2)
print(x-2)
print(x*2)
print(x/2)
print(x**2)

tensor([[2.2332, 2.4047, 2.2162],
        [2.9927, 2.4128, 2.5938]])
tensor([[-1.7668, -1.5953, -1.7838],
        [-1.0073, -1.5872, -1.4062]])
tensor([[0.4664, 0.8093, 0.4325],
        [1.9854, 0.8255, 1.1876]])
tensor([[0.1166, 0.2023, 0.1081],
        [0.4963, 0.2064, 0.2969]])
tensor([[0.0544, 0.1637, 0.0468],
        [0.9854, 0.1704, 0.3526]])


In [ ]:
#element wise operations
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

tensor([[1.3057, 0.3223, 0.1838],
        [0.9794, 1.7459, 0.4245]])
tensor([[-0.0801, -0.0184, -0.0931],
        [ 0.0276,  0.2498,  0.3523]])
tensor([[0.4246, 0.0259, 0.0063],
        [0.2396, 0.7464, 0.0140]])
tensor([[ 0.8844,  0.8920,  0.3275],
        [ 1.0580,  1.3339, 10.7529]])
tensor([[0.7122, 0.7254, 0.6516],
        [0.7214, 0.9984, 0.9664]])


In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
## Statistical operations

In [ ]:
## Matrix mul

In [ ]:
f = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.int32)
g = torch.randint(size = (3,2), low = 0, high = 10, dtype = torch.int32)
print(f)
print(g)

tensor([[4, 8, 9],
        [6, 2, 1]], dtype=torch.int32)
tensor([[3, 2],
        [7, 4],
        [9, 0]], dtype=torch.int32)


In [ ]:
c = torch.tensor([1,2,3])
d = torch.tensor([1,2,3])
torch.matmul(c,d)

tensor(14)

In [ ]:
h = torch.transpose(f, 0, 1) #we want to swap 0 with 1

In [ ]:
h

tensor([[4, 6],
        [8, 2],
        [9, 1]], dtype=torch.int32)

inplace operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [ ]:
m + n # doing this will create new tensor which in return occupy some memory instead below we will do the inplace operations

tensor([[1.9156, 1.5612, 1.6520],
        [2.1426, 2.2074, 1.0961]])

In [ ]:
n.add_(m)

tensor([[1.3010, 0.9613, 1.1507],
        [1.2030, 1.3418, 0.5754]])

In [ ]:
m.add_(n)

tensor([[1.9156, 1.5612, 1.6520],
        [2.1426, 2.2074, 1.0961]])

In [ ]:
#adding and _ after the function name will perform inplace operations

In [ ]:
torch.relu_(m)

tensor([[1.9156, 1.5612, 1.6520],
        [2.1426, 2.2074, 1.0961]])

# Tensor operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
#creating variable where we will store our GPU
device = torch.device('cuda')

In [ ]:
torch.rand((2,3), device = device)

tensor([[0.3344, 0.2640, 0.2119],
        [0.0582, 0.3720, 0.1818]], device='cuda:0')

In [ ]:
#moving CPU tensor on GPU

In [ ]:
a = torch.rand(2,3)

In [ ]:
b = a.to(device)

In [ ]:
b +5

tensor([[5.2024, 5.5731, 5.7191],
        [5.4067, 5.7301, 5.6276]], device='cuda:0')