## PLAN OF ACTION

- Revision
- improvements
- The nn module
- The torch.optim module

### Improvements

- Building the NN using module
- using built-in activation fn
- using buil-in loss function
- using built-in optimizer

## Read wriiten notes about nn module

### single neuron network

In [ ]:
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    # self.relu = nn.ReLU()
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [ ]:
features = torch.rand(10,5)

model = Model(features.shape[1])
model(features)

tensor([[0.5008],
        [0.5063],
        [0.4506],
        [0.5621],
        [0.4689],
        [0.4682],
        [0.4653],
        [0.5391],
        [0.4670],
        [0.5407]], grad_fn=<SigmoidBackward0>)

In [ ]:
#show model weights

model.linear.weight

Parameter containing:
tensor([[-0.2843,  0.0030,  0.2207,  0.0519,  0.3808]], requires_grad=True)

In [ ]:
model.linear.bias

Parameter containing:
tensor([-0.1975], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

neural network

In [ ]:
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [ ]:
features = torch.rand(10,5)

model = Model(features.shape[1])
model(features)

tensor([[0.4446],
        [0.4628],
        [0.4755],
        [0.4619],
        [0.4592],
        [0.4611],
        [0.4731],
        [0.4640],
        [0.4653],
        [0.4449]], grad_fn=<SigmoidBackward0>)

In [ ]:
#show model weights

model.linear1.weight

Parameter containing:
tensor([[-0.1603,  0.1987,  0.1157,  0.3693, -0.2450],
        [-0.1120, -0.3046, -0.0754,  0.3011, -0.0237],
        [-0.0064, -0.0444, -0.0289,  0.2845,  0.3361]], requires_grad=True)

In [ ]:
model.linear1.bias

Parameter containing:
tensor([-0.3206, -0.1052,  0.3065], requires_grad=True)

In [ ]:
model.linear2.weight

Parameter containing:
tensor([[ 0.1412,  0.3370, -0.3304]], requires_grad=True)

In [ ]:
model.linear2.bias

Parameter containing:
tensor([0.0462], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

#using sequential container read notes, we put all our layers in this seq container
#all layers will become sequential
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

#now we simply have to do since our network is stored in seq container
  def forward(self, features):
    out = self.network(features)

    return out